name: Release package
on:
  release:
    types:
      - released

jobs:
  release-bins:
    name: release ${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.runs-on }}
    permissions:
      contents: write
    strategy:
      matrix:
        platform:
          - os-name: FreeBSD-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-freebsd

          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl

          - os-name: Linux-riscv64
            runs-on: ubuntu-24.04
            target: riscv64gc-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@v2
        with:
           tool: cargo-bump
      - name: Install build tools
        run: sudo apt-get update -y && sudo apt-get install -y build-essential
      - name: Bumping version
        run: cargo bump "${{ github.ref_name }}"
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.
          # Note that glob pattern is not supported yet.
          bin: ldfm
          target: ${{matrix.platform.target}}
          tar: unix
          include: LICENSE,README.md
          # (required) GitHub token for uploading assets to GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}


  release-crates:
    runs-on: ubuntu-latest
    needs: "release-bins"
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@v2
        with:
           tool: cargo-bump
      - name: Bumping version
        run: cargo bump "${{ github.ref_name }}"
      - name: Publish crate
        run: cargo publish --token "${{ secrets.CARGO_TOKEN }}" --allow-dirty
