name: Release package
on:
  release:
    types:
      - released

jobs:
  release-bins:
    name: release ${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      matrix:
        platform:
          - os-name: FreeBSD-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-freebsd

          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl

          - os-name: Linux-riscv64
            runs-on: ubuntu-24.04
            target: riscv64gc-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@v2
        with:
           tool: cargo-bump
      - name: Install build tools
        run: sudo apt-get update -y && sudo apt-get install -y build-essential
      - name: Bumping version
        run: cargo bump "${{ github.ref_name }}"
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ldfm
          changes-file: ""
          release-tag-prefix: "${{ github.ref_name }}"
          target: ${{ matrix.platform.target }}

  release-crates:
    runs-on: ubuntu-latest
    needs: "release-bins"
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@v2
        with:
           tool: cargo-bump
      - name: Bumping version
        run: cargo bump "${{ github.ref_name }}"
      - name: Publish crate
        run: cargo publish --token "${{ secrets.CARGO_TOKEN }}"
